import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import cloudcashIcon from "../assets/cloudcash.svg";
import overviewImg from "@/assets/overview.svg";
import transactionsImg from "@/assets/transactions.svg";
import cardsImg from "@/assets/cards.svg";
import invoicesImg from "@/assets/invoices.svg";
import goalsImg from "@/assets/goals.svg";
import settingsImg from "@/assets/settings.svg";
import upgradeImg from "@/assets/upgrade-icon.svg";
import upgradeArrowImg from "@/assets/button-up-arrow.svg";
import { Button } from "@/components/ui/button";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Financial Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="min-h-screen flex md:flex-row flex-col bg-white">
          <aside className="w-full md:w-64 bg-white shadow-md relative flex flex-col md:items-start items-center justify-between">
            <div className="flex flex-col md:items-start items-center justify-between ">
              <div className="p-6 font-bold text-xl">
                <Image src={cloudcashIcon as string} alt="cloudcash" />
              </div>
              <nav className="p-6">
                <ul>
                  <li className="mb-2 bg-[#F0F7FF] flex flex-row items-center justify-start gap-2 rounded-md py-1 px-2">
                    <Image src={overviewImg} alt="overview" />
                    <a
                      href="/"
                      className="font-Lato text-[14px] font-medium leading-[16.8px] text-[#197BBD]"
                    >
                      Overview
                    </a>
                  </li>
                  <li className="mb-2 hover:bg-[#F0F7FF] flex flex-row items-center justify-start gap-2 rounded-md py-1 px-2 ">
                    <Image src={transactionsImg} alt="transactions" />
                    <a
                      href="/transactions"
                      className=" font-Lato text-[14px] font-medium leading-[16.8px] text-[#C7C7C7] hover:text-[#197BBD]"
                    >
                      Transactions
                    </a>
                  </li>
                  <li className="mb-2 hover:bg-[#F0F7FF] flex flex-row items-center justify-start gap-2 rounded-md py-1 px-2 ">
                    <Image src={cardsImg} alt="cards" />
                    <a
                      href="#"
                      className=" font-Lato text-[14px] font-medium leading-[16.8px] text-[#C7C7C7] hover:text-[#197BBD]"
                    >
                      Cards
                    </a>
                  </li>
                  <li className="mb-2 hover:bg-[#F0F7FF] flex flex-row items-center justify-start gap-2 rounded-md py-1 px-2 ">
                    <Image src={invoicesImg} alt="invoices" />
                    <a
                      href="#"
                      className=" font-Lato text-[14px] font-medium leading-[16.8px] text-[#C7C7C7] hover:text-[#197BBD]"
                    >
                      Invoices
                    </a>
                  </li>
                  <li className="mb-2 hover:bg-[#F0F7FF] flex flex-row items-center justify-start gap-2 rounded-md py-1 px-2 ">
                    <Image src={goalsImg} alt="goals" />
                    <a
                      href="#"
                      className=" font-Lato text-[14px] font-medium leading-[16.8px] text-[#C7C7C7] hover:text-[#197BBD]"
                    >
                      Goals
                    </a>
                  </li>
                  <li className="mb-2 hover:bg-[#F0F7FF] flex flex-row items-center justify-start gap-2 rounded-md py-1 px-2 ">
                    <Image src={settingsImg} alt="settings" />
                    <a
                      href="#"
                      className=" font-Lato text-[14px] font-medium leading-[16.8px] text-[#C7C7C7] hover:text-[#197BBD]"
                    >
                      Settings
                    </a>
                  </li>
                </ul>
              </nav>
            </div>

            <div className=" p-4 w-full flex flex-col items-center gap-2">
              <Image src={upgradeImg} alt="upgrade" />
              <Button className="bg-yellow-500 text-[#404040] p-4 rounded-2xl font-quicksand text-[11.14px] font-medium leading-[13.93px] ">
                Upgrade to premium
                <Image
                  src={upgradeArrowImg}
                  alt="upgrade"
                  className="h-[7.28px] w-[7.28px] ml-1"
                />
              </Button>
            </div>
          </aside>
          <div className="w-full md:w-[2px] bg-gray-100 relative"></div>
          <div className="w-full p-6">{children}</div>
        </div>
      </body>
    </html>
  );
}
